resolve clarify borg check --verify-data (#5808)
borgbackup/borg pull request #5860
Opened 2021-06-18 17:59 UTC by braewoods

This should close #5808 and count towards completion of #5129.

2021-06-18 19:10 UTC, ThomasWaldmann requested changes
maybe re-read the ticket.

the repository part of the check is a very simple and low-level check. no crypto there, just some crc32 checking etc.

the crypto stuff that also needs the key is in the archives part of the check. also --verify-data happens in the archives part of the check.

if none of the --repository-only or --archives-only options are given. borg does both checks, first the lowlevel repo check, then the higher level archives check.

2021-06-18 19:10 UTC, ThomasWaldmann commented on docs/usage/check.rst.inc
> +  ``--verify-data`` option.
not correct.

2021-06-18 19:10 UTC, ThomasWaldmann commented on docs/usage/check.rst.inc
> +slow. This option also implies ``--archives-only``.
not correct.

2021-06-18 19:10 UTC, ThomasWaldmann commented on src/borg/archiver.py
> +          ``--verify-data`` option.
not correct.

2021-06-18 19:10 UTC, ThomasWaldmann commented on src/borg/archiver.py
> +        slow. This option also implies ``--archives-only``.
not correct.

2021-06-18 20:00 UTC, braewoods commented
Is this any better?

2021-06-18 21:54 UTC, ThomasWaldmann commented on docs/usage/check.rst.inc
> +  are documented below.
btw you do not need to update these files, that is done automatically at release time (auto-generated from archiver.py).

2021-06-18 21:54 UTC, ThomasWaldmann commented on src/borg/archiver.py
> +          are documented below.
yup, much better!

2021-06-19 12:08 UTC, merged

2021-06-19 12:08 UTC, ThomasWaldmann commented
thanks!