Clarify usage of patternfile roots
borgbackup/borg pull request #6242
Opened 2022-02-05 03:48 UTC by bobthebadguy

See #6231. Clarifies what patternfile roots actually do with examples.

2022-02-05 12:34 UTC, ThomasWaldmann commented on docs/usage/help.rst.inc
> +
maybe add the borg command that uses this pattern file.

2022-02-06 02:38 UTC, bobthebadguy commented
I still feel like this could be a bit clearer

2022-02-06 14:29 UTC, ThomasWaldmann requested changes
most important: read the comment at the top of the file you are editing.

just use full-text search the right place, likely it is in `src/borg/archiver.py`.

2022-02-06 14:29 UTC, ThomasWaldmann commented on docs/usage/help.rst.inc
> +    may specify the backup roots (starting points), pattern files, and patterns for inclusion/exclusion.
this paragraph is talking about the patterns specifically (not the command line in general), so we are already "in" the pattern file, so you can't specify a pattern file there.

so I'ld suggest to just remove this change.

2022-02-06 14:29 UTC, ThomasWaldmann commented on docs/usage/help.rst.inc
> +
you say "same thing", so people might expect this is precisely doing the same thing as the previous example, which it does not.

maybe adjust it so it really does exactly the same thing?

2022-02-06 20:27 UTC, bobthebadguy commented
Did I mess up the indentation? 
Sorry about that, should have read more closely

2022-02-06 20:31 UTC, ThomasWaldmann commented on src/borg/archiver.py
> +            As another example, you could do the same thing in either of these ways::
"same" might get misunderstood as a backreference to the previous example (lines before 2420).

maybe rather say:

Here is another example that shows how recursion roots and excludes can be given either directly on the command line or in a patternfile.

(with that, you could drop the comments from 2424 and 2426)

2022-02-06 20:33 UTC, ThomasWaldmann commented on src/borg/archiver.py
> +            This allows you to share the same patterns between multiple repositories without needing to specify them on the command line.\n\n''')
borg can output this help directly on the terminal.
if a line is longer than 80 chars, rather continue on next line.

2022-02-06 20:37 UTC, ThomasWaldmann commented
there seems to be a conflict now with other master branch changes.

and because you have committed to directly to your master branch, this is a little tricky to fix now...

maybe just tell when you've finished your changes and i'll try to fix it.

2022-02-06 22:38 UTC, ThomasWaldmann commented
now indentation is wrong again. most stuff will appear inside a code block now instead as normal text.

2022-02-06 22:39 UTC, ThomasWaldmann commented
```
cd docs ; make clean ; make html
```
then look at the local html files with a browser.

2022-02-07 02:37 UTC, bobthebadguy commented
It looks like that fixed it?

Thanks for all your help with this and sorry for the trouble

2022-02-07 02:41 UTC, ThomasWaldmann approved these changes
LGTM

2022-02-07 19:53 UTC, merged

2022-02-07 19:53 UTC, ThomasWaldmann commented
Thanks!

2022-02-08 09:04 UTC, hexagonrecursion commented
I plan to backport this today