docs: Clarify on-disk order and size of log entry fields (1.1)
borgbackup/borg pull request #6360
Opened 2022-02-25 12:20 UTC by hexagonrecursion

* This is a backport of https://github.com/borgbackup/borg/pull/6357

2022-02-25 20:01 UTC, ThomasWaldmann requested changes
thanks for trying to get 1.1 and 1.2/master better in sync again, but some stuff does not apply to 1.1.x.

2022-02-25 20:01 UTC, ThomasWaldmann commented on docs/internals/data-structures.rst
> +exclusive locks). Inside this directory, there is a file indicating
it's still os.mkdir in 1.1.x.

2022-02-25 20:09 UTC, hexagonrecursion commented
I am confused. I only intended to backport #6357. I am not sure where the rest of the diff came from.

2022-02-25 20:11 UTC, ThomasWaldmann commented
Interesting. Do you use `git cherry-pick CHANGESET`?

2022-02-25 20:13 UTC, hexagonrecursion commented
Yes. Is there something I do not understand about it?

2022-02-25 20:20 UTC, ThomasWaldmann commented
Usually that just works. Or you get some conflicts you have to fix carefully.

2022-02-26 14:20 UTC, hexagonrecursion commented
I see what happened. There was a merge conflict. I have looked at it and decided that I want to resolve it by replacing the conflict with the changes from the patch I am backporting. I have followed [this advice](https://stackoverflow.com/a/21777677/14516046) and executed `git checkout --theirs -- docs/`. This did not do what I expected - I expected it to only resolve the conflicts, but it looks like it copied the entire file from 1.2 to 1.1. I am very sorry.

2022-02-26 19:17 UTC, ThomasWaldmann approved these changes
LGTM

2022-02-26 19:17 UTC, merged