xattrs / extended stat: improve exception handling (master
borgbackup/borg pull request #7008
Opened 2022-09-07 07:31 UTC by KN4CK3R

forward port of #6990

The different quotes in both branches made some trouble but should be fine now.

2022-09-07 12:41 UTC, ThomasWaldmann requested changes

2022-09-07 12:41 UTC, ThomasWaldmann commented on src/borg/testsuite/archiver.py
> +        not xattr.XATTR_FAKEROOT, reason="xattr not supported on this system or on this version of " "fakeroot"
hmm, if that's what black made out of this, guess we better merge the 2 strings into 1.

see also the other 2 places with same string.

2022-09-09 19:14 UTC, ThomasWaldmann commented on src/borg/testsuite/archiver.py
> +        not xattr.XATTR_FAKEROOT, reason="xattr not supported on this system or on this version of " "fakeroot"
@KN4CK3R did you see my feedback?

2022-09-09 22:28 UTC, ThomasWaldmann approved these changes
fixed the cosmetics myself so i can merge this soon.

2022-09-09 22:52 UTC, merged

2022-09-10 13:00 UTC, KN4CK3R commented
Sorry, was not a home.