Fix repository tests on Windows
borgbackup/borg pull request #7141
Opened 2022-11-10 18:00 UTC by RayyanAnsari

2022-11-10 21:03 UTC, ThomasWaldmann requested changes

2022-11-10 21:03 UTC, ThomasWaldmann commented on src/borg/repository.py
> +                self.close_segment()
also, i guess you need to:
```
    def cleanup(self, transaction_id):
        """Delete segment files left by aborted transactions"""
        self.close_segment()  # note: might increment self.segment
        self.segment = transaction_id + 1
        count = 0
        for segment, filename in self.segment_iterator(reverse=True):
            if segment > transaction_id:
                self.delete_segment(segment)
                count += 1
            else:
                break
        logger.debug("Cleaned up %d uncommitted segment files (== everything after segment %d).", count, transaction_id)
```

Please verify that again in the source code and run the tests again.

2022-11-15 17:51 UTC, ThomasWaldmann requested changes
great you could fix it!

some minor things which I found....

2022-11-15 17:57 UTC, RayyanAnsari commented on src/borg/crypto/file_integrity.py
> +            self.file_fd.close()
so here, there should be a check on override_fd to see if it was opened by the caller or in this class?

2022-11-15 18:16 UTC, ThomasWaldmann commented on src/borg/testsuite/repository.py
>          os.unlink(os.path.join(self.tmppath, "repository", "data", "0", str(segment)))
```
    def delete_segment(self, segment):
>       del self.repository.io.fds[segment]
E       AttributeError: 'RemoteRepository' object has no attribute 'io'
```

2022-11-16 17:40 UTC, ThomasWaldmann approved these changes
LGTM

2022-11-16 17:43 UTC, merged