[WIP] Add debug commands for repoobj id_hash/parse/format
borgbackup/borg pull request #7416
Opened 2023-03-07 20:40 UTC by shalearkane

Implements #7406
[x] id-hash
[ ] parse-obj
[ ] format-obj
[ ] Tests

2023-03-07 21:11 UTC, ThomasWaldmann requested changes
Looks good overall, but I guess we can simplify it a bit and also make the wording consistent with borg 1.2.x.

2023-03-07 21:11 UTC, ThomasWaldmann commented on src/borg/archiver/debug_cmd.py
> +        repo_objs = RepoObj(key)
if you used `manifest=True`, would you get this "for free"?

2023-03-07 21:11 UTC, ThomasWaldmann commented on src/borg/archiver/debug_cmd.py
> +            This command reads a plaintext file and computes object id from it
This command computes the id-hash for some file content.

(from 1.2-maint)

2023-03-07 21:11 UTC, ThomasWaldmann commented on src/borg/archiver/debug_cmd.py
> +        """calculate object id of a given plaintext file"""
"""compute id-hash for file contents"""

(from 1.2-maint)

2023-03-07 21:11 UTC, ThomasWaldmann commented on src/borg/archiver/debug_cmd.py
> +        subparser.add_argument("path", metavar="PATH", type=str, help="plaintext file to calculate object id from")
help='content for which the id-hash shall get computed')

(from 1.2-maint)

2023-03-12 13:50 UTC, ThomasWaldmann commented
hi @shalearkane, do you still work on this?

guess you can ignore my feedback about id-hash and have a look at #7436 - looks like there was some parallel work and they already solved the id-hash part.

i guess i can merge #7436 soon and maybe easiest for you is to update your local master branch and then start a new PR, if you want to work on parse/format.

2023-03-13 13:08 UTC, shalearkane commented
Yes definitely. I am closing this pull request and opening another.

2023-03-13 13:08 UTC, closed without merging