WIP: Fixes config dir compatibility issue identified in #7445
borgbackup/borg pull request #7448
Opened 2023-03-17 21:32 UTC by nain-F49FF806

2023-03-20 19:37 UTC, ThomasWaldmann requested changes

2023-03-20 19:37 UTC, ThomasWaldmann commented on src/borg/testsuite/helpers.py
> +    monkeypatch.delenv("XDG_CACHE_HOME", raising=False)
considering the cache and config tests are quite similar, the way the env vars are set up should be done in precisely the same way.

except if:
- you find a bug or shortcoming
- there is a difference requiring it to be different

2023-03-25 04:44 UTC, nain-F49FF806 commented on src/borg/testsuite/helpers.py
> +    monkeypatch.delenv("XDG_CACHE_HOME", raising=False)
I think some of the config compat test code is a bit redundant. Like the two `if` blocks when there need be only one (it's the same condition twice). Is there something I am missing that needs the two?

So I simplified the implementation for cache test hoping it'd be easier to follow. While retaining the order of del and set of the environment variables. 

I would propose to change the config test to match the latter ie cache one at L680.   
Does that seem fine?

[Sending a patch in a moment]

2023-03-25 17:07 UTC, ThomasWaldmann commented on src/borg/testsuite/helpers.py
>          # fails on macOS: assert '/Users/tw/Library/Application Support/borg' == '/var/tmp/.config1/borg'
if you change the code, you also need to fix the path in the comment below in the same way.

2023-03-25 17:07 UTC, ThomasWaldmann commented on src/borg/testsuite/helpers.py
> +    monkeypatch.delenv("XDG_CACHE_HOME", raising=False)
The `if`s can be merged, sure.

Guess the code is now in good sync.

2023-03-25 17:07 UTC, ThomasWaldmann commented on src/borg/testsuite/helpers.py
> +        # Please try on darwin and win32 and update comment accordingly
This needs to be done still - both macOS and win32 could be check via github CI and some temporary commit that fails, so one sees the values and can write some similar comments as seen in the config compat test.

2023-03-29 20:20 UTC, ThomasWaldmann approved these changes
LGTM!

2023-03-29 22:24 UTC, merged

2023-03-29 22:24 UTC, ThomasWaldmann commented
Thanks!