Added pre-commit for linting purposes. Fixes #7476
borgbackup/borg pull request #7547
Opened 2023-05-06 03:54 UTC by sashadev-sky

Includes changes from #7477

2023-05-06 12:16 UTC, ThomasWaldmann requested changes
thanks for backporting this.

sorry, maybe i missed to mention it, but the `black` part should not be part of the backport.

2023-05-06 12:16 UTC, ThomasWaldmann commented on .pre-commit-config.yaml
> +    -   id: black
we won't backport the `black` releated part of this and won't globally change src formatting in 1.2 branch.

2023-05-06 12:16 UTC, ThomasWaldmann commented on .pre-commit-config.yaml
> +        files: '(src|scripts|conftest.py)'
good, we'll take this for 1.2.

2023-05-06 12:16 UTC, ThomasWaldmann commented on docs/development.rst
> +This project utilizes pre-commit to format and lint code before it is committed.
remove "format and ".

2023-05-07 22:53 UTC, sashadev-sky commented
@ThomasWaldmann updated!

2023-05-08 13:28 UTC, ThomasWaldmann approved these changes
LGTM!

2023-05-08 13:28 UTC, merged