Archive pytest conversion
borgbackup/borg pull request #7661
Opened 2023-06-22 00:41 UTC by bigtedde

Started with a couple test parameterizations. Will parameterize more tests, trying to ensure I don't impact readability in the process.

2023-06-22 00:43 UTC, bigtedde commented on src/borg/testsuite/archive.py
> -    stats.show_progress(item=Item(path="foo"), final=False, stream=out)
`final` is set to `false` by default in `show_progress`, so removing it should have no effect here.

2023-06-22 00:48 UTC, bigtedde commented
I spent a considerable amount of time trying to parameterize `test_get_item_uid_gid`, but found it both wasn't easily readable and didn't work.

2023-07-10 13:21 UTC, ThomasWaldmann requested changes
Guess we can merge this, just please move the comment to where it belongs.

2023-07-10 13:21 UTC, ThomasWaldmann commented on src/borg/testsuite/archive.py
> +    ],  # test long item path which exceeds 80 characters
the comment belongs to line 42. so either put it there (if it does not exceed max line length) or above that line.

2023-07-10 13:23 UTC, ThomasWaldmann commented
BTW, if you think something is finished, switch it from draft to "ready for review".

2023-07-10 23:14 UTC, ThomasWaldmann approved these changes

2023-07-10 23:14 UTC, merged

2023-07-10 23:15 UTC, ThomasWaldmann commented
Thanks!